id: P009603
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25467
  title: རི་མོར་བལྟས་ནས་ལུས་རྩལ་རྣམ་གྲངས་ངོས་འཛིན་པ།
  author: ''
  volumes:
    04f512f091154648a55e1c8f43a3a67a:
      image_group_id: I1KG25469
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
